#!/bin/bash
#
# This server hook enforces that committer have applied uncrustify on changed
# files. For fast-forward pushes it checks files for every commit from oldrev
# to newrev. For pushes with zero oldrev it uses commits from HEAD to newrev.
#

# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

result=0

# --- Safety check
if [ -z "$GIT_DIR" ]; then
    echo "Don't run this script from the command line." >&2
    echo " (if you want, you could supply GIT_DIR then run" >&2
    echo "  $0 <ref> <oldrev> <newrev>)" >&2
    exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ]; then
    echo "usage: $0 <ref> <oldrev> <newrev>" >&2
    exit 1
fi

if [ "$oldrev" = "0000000000000000000000000000000000000000" ]; then
    oldrev=HEAD
fi

if [ "$newrev" = "0000000000000000000000000000000000000000" ]; then
    exit 0
fi

git rev-parse --short HEAD 2>/dev/null
if [ $? -ne 0 ]; then
    # There is no HEAD yet
    exit 0
fi

function skipFile {
    skipDirs=$1
    f=$2
    while read d; do
	if [ "${f:0:${#d}}" == "$d" ]; then
	    return 0
	else
	    return 1
	fi
    done <<< "$skipDirs"
}

uncrustifycfg=$(mktemp)

for rev in $(git log --pretty="format:%H" $oldrev..$newrev); do
    git show $rev:uncrustify.cfg > "$uncrustifycfg"

    skipdirs=$(git show --pretty="format:" --name-only $rev | egrep 'nouncrustify$' | xargs -I {} dirname './{}/' | sed 's/$/\//g')

    while read f; do
	if skipFile "$skipDirs" "$f"; then
	    continue
	fi
	
	cmp -s <(git show "$rev:$f") <(git show "$rev:$f" | uncrustify -q -l CPP -c "$uncrustifycfg")
	if [ $? -ne 0 ]; then
	    result=1
	    echo "You must run uncrustify for $f in $rev"
	fi
    done < <(git show --pretty="format:" --name-only $rev | egrep '\.h$|\.cpp$')
done

rm "$uncrustifycfg"

exit 1
# --- Finished
exit $result
